### Buscar shows por un criterio (Inciso A)
GET http://localhost:8080/api/shows/search?search_query=girls
### Obtener un show específico por ID con caché (Inciso B)
GET http://localhost:8080/api/shows/250
### Crear un comentario y calificación (Punto C)
POST http://localhost:8080/api/shows/comment?show_id=250&comment=Excelente serie de Disney XD&rating=5
