spring.application.name=tvmaze-middleware
mongodb.username=isaac_admin
mongodb.password=TuPasswordSeguro123
mongodb.host=cluster0.youpxwu.mongodb.net
mongodb.database=tvmaze_db
tvmaze.api.base-url=https://api.tvmaze.com